### ISSUE TITLE
Installing Merchello package takes you to FastTrack

### ISSUE THREAD

**Issue by darrenkras** [Merchello/Merchello#2172]
Please see attached PDF. I crashed my system by following the logical steps for downloading Merchello.

Currently, if you search for the Merchello package in the Umbraco back office you arrive at the Merchello core package page. After clicking install you are directed to install FastTrack. Is this package FastTrack or Merchello? Ive been told in a previous ticket I installed FastTrack and not Merchello, but how else would one arrive at the Merchello package?

[Installing Merchello Issue.pdf](https://github.com/Merchello/Merchello/files/2191439/Installing.Merchello.Issue.pdf)

**Comment by YodasMyDad** [comment]
This is fixed. I've removed FastTrack from Umbraco

**Comment by aram-aramyan** [comment]
The issue is not solved. When I try to install Merchello from "Packages" it actually installs FastTrack.
But when I download it from our.umbraco.org and "Install local" it is installed correctly.

**Comment by YodasMyDad** [comment]
There is a bug with our.Umbraco it's choosing version 2.6 for some reason. Just download the zip from our.umbraco and install that way.
